### ISSUE TITLE
Visualizer not working properly for AudioFormat.ENCODING_PCM_16BIT configuration.

### ISSUE THREAD

**Issue by TalViewDev** [bogerchan/Nier-Visualizer#24]
Visualizer not working properly for AudioFormat.ENCODING_PCM_16BIT configuration. However its working fine for 8 bit config.

**Comment by bogerchan** [comment]
I have fixed this in latest version, please try it. :D

**Comment by KvasMax** [comment]
@bogerchan  Hi. The latest commit was on Feb 12. Did you push this changes or i am missing something?

**Comment by bogerchan** [comment]
Hi, thanks for your feedback. I think the `master` is the latest version now.

**Comment by netagivony** [comment]
@bogerchan ENCODING_PCM_16BIT still don't working...
I'm using ENCODING_PCM_16BIT with your demoActivity as example.

**Comment by netagivony** [comment]
@KvasMax did you fix that issue?
